"""External resource hierarchy detection for architecture validation.

Provides parent-child resource type mappings used by validate_architecture.py
to detect resources that should be nested but are stored flat in the DB.

The mappings are primarily sourced from the resource_types table (parent_type
column) but also include supplementary static entries for resources whose
parent relationships can be inferred from Terraform attribute names alone.
"""

from __future__ import annotations

from typing import Dict, Optional

# ---------------------------------------------------------------------------
# HIERARCHY_CONFIG
# Structure: {child_type: {"parent_type": str, "parent_field": str}}
# parent_field is the Terraform attribute that references the parent resource.
# ---------------------------------------------------------------------------
HIERARCHY_CONFIG: Dict[str, Dict[str, str]] = {
    # --- Azure ---
    "azurerm_subnet": {"parent_type": "azurerm_virtual_network", "parent_field": "virtual_network_name"},
    "azurerm_network_security_rule": {"parent_type": "azurerm_network_security_group", "parent_field": "network_security_group_name"},
    "azurerm_network_interface": {"parent_type": "azurerm_subnet", "parent_field": "subnet_id"},
    "azurerm_network_interface_security_group_association": {"parent_type": "azurerm_network_security_group", "parent_field": "network_security_group_id"},
    "azurerm_mssql_database": {"parent_type": "azurerm_mssql_server", "parent_field": "server_id"},
    "azurerm_mssql_firewall_rule": {"parent_type": "azurerm_mssql_server", "parent_field": "server_id"},
    "azurerm_mysql_database": {"parent_type": "azurerm_mysql_server", "parent_field": "server_name"},
    "azurerm_mysql_flexible_database": {"parent_type": "azurerm_mysql_flexible_server", "parent_field": "server_name"},
    "azurerm_postgresql_database": {"parent_type": "azurerm_postgresql_server", "parent_field": "server_name"},
    "azurerm_cosmosdb_sql_database": {"parent_type": "azurerm_cosmosdb_account", "parent_field": "account_name"},
    "azurerm_cosmosdb_sql_container": {"parent_type": "azurerm_cosmosdb_account", "parent_field": "account_name"},
    "azurerm_storage_container": {"parent_type": "azurerm_storage_account", "parent_field": "storage_account_name"},
    "azurerm_storage_blob": {"parent_type": "azurerm_storage_container", "parent_field": "storage_container_name"},
    "azurerm_storage_queue": {"parent_type": "azurerm_storage_account", "parent_field": "storage_account_name"},
    "azurerm_storage_share": {"parent_type": "azurerm_storage_account", "parent_field": "storage_account_name"},
    "azurerm_key_vault_key": {"parent_type": "azurerm_key_vault", "parent_field": "key_vault_id"},
    "azurerm_key_vault_secret": {"parent_type": "azurerm_key_vault", "parent_field": "key_vault_id"},
    "azurerm_key_vault_certificate": {"parent_type": "azurerm_key_vault", "parent_field": "key_vault_id"},
    "azurerm_app_service": {"parent_type": "azurerm_app_service_plan", "parent_field": "app_service_plan_id"},
    "azurerm_function_app": {"parent_type": "azurerm_app_service_plan", "parent_field": "app_service_plan_id"},
    "azurerm_linux_function_app": {"parent_type": "azurerm_app_service_plan", "parent_field": "service_plan_id"},
    "azurerm_windows_function_app": {"parent_type": "azurerm_app_service_plan", "parent_field": "service_plan_id"},
    "azurerm_api_management_api": {"parent_type": "azurerm_api_management", "parent_field": "api_management_name"},
    "azurerm_api_management_api_operation": {"parent_type": "azurerm_api_management_api", "parent_field": "api_name"},
    "azurerm_api_management_product": {"parent_type": "azurerm_api_management", "parent_field": "api_management_name"},
    "azurerm_api_management_backend": {"parent_type": "azurerm_api_management", "parent_field": "api_management_name"},
    "azurerm_kubernetes_cluster_node_pool": {"parent_type": "azurerm_kubernetes_cluster", "parent_field": "kubernetes_cluster_id"},
    "azurerm_lb_rule": {"parent_type": "azurerm_lb", "parent_field": "loadbalancer_id"},
    "azurerm_lb_probe": {"parent_type": "azurerm_lb", "parent_field": "loadbalancer_id"},
    "azurerm_automation_runbook": {"parent_type": "azurerm_automation_account", "parent_field": "automation_account_name"},
    # --- AWS ---
    "aws_subnet": {"parent_type": "aws_vpc", "parent_field": "vpc_id"},
    "aws_instance": {"parent_type": "aws_subnet", "parent_field": "subnet_id"},
    "aws_network_interface": {"parent_type": "aws_subnet", "parent_field": "subnet_id"},
    "aws_eks_cluster": {"parent_type": "aws_subnet", "parent_field": "subnet_ids"},
    "aws_security_group_rule": {"parent_type": "aws_security_group", "parent_field": "security_group_id"},
    "aws_vpc_security_group_ingress_rule": {"parent_type": "aws_security_group", "parent_field": "security_group_id"},
    "aws_vpc_security_group_egress_rule": {"parent_type": "aws_security_group", "parent_field": "security_group_id"},
    "aws_s3_bucket_acl": {"parent_type": "aws_s3_bucket", "parent_field": "bucket"},
    "aws_s3_bucket_policy": {"parent_type": "aws_s3_bucket", "parent_field": "bucket"},
    "aws_s3_bucket_public_access_block": {"parent_type": "aws_s3_bucket", "parent_field": "bucket"},
    "aws_s3_bucket_ownership_controls": {"parent_type": "aws_s3_bucket", "parent_field": "bucket"},
    "aws_s3_bucket_cors_configuration": {"parent_type": "aws_s3_bucket", "parent_field": "bucket"},
    "aws_api_gateway_resource": {"parent_type": "aws_api_gateway_rest_api", "parent_field": "rest_api_id"},
    "aws_api_gateway_method": {"parent_type": "aws_api_gateway_resource", "parent_field": "resource_id"},
    "aws_api_gateway_integration": {"parent_type": "aws_api_gateway_method", "parent_field": "resource_id"},
    "aws_api_gateway_deployment": {"parent_type": "aws_api_gateway_rest_api", "parent_field": "rest_api_id"},
    "aws_api_gateway_stage": {"parent_type": "aws_api_gateway_rest_api", "parent_field": "rest_api_id"},
    "aws_apigatewayv2_integration": {"parent_type": "aws_apigatewayv2_api", "parent_field": "api_id"},
    "aws_apigatewayv2_route": {"parent_type": "aws_apigatewayv2_api", "parent_field": "api_id"},
    "aws_apigatewayv2_stage": {"parent_type": "aws_apigatewayv2_api", "parent_field": "api_id"},
    "aws_lb_listener": {"parent_type": "aws_lb", "parent_field": "load_balancer_arn"},
    "aws_lb_target_group": {"parent_type": "aws_lb", "parent_field": "load_balancer_arn"},
    "aws_lb_target_group_attachment": {"parent_type": "aws_lb_target_group", "parent_field": "target_group_arn"},
    "aws_sns_topic_subscription": {"parent_type": "aws_sns_topic", "parent_field": "topic_arn"},
    "aws_db_subnet_group": {"parent_type": "aws_vpc", "parent_field": "vpc_id"},
    "aws_elasticache_subnet_group": {"parent_type": "aws_vpc", "parent_field": "vpc_id"},
    # --- GCP ---
    "google_compute_instance": {"parent_type": "google_compute_network", "parent_field": "network"},
    "google_compute_subnetwork": {"parent_type": "google_compute_network", "parent_field": "network"},
    "google_compute_firewall": {"parent_type": "google_compute_network", "parent_field": "network"},
    "google_compute_forwarding_rule": {"parent_type": "google_compute_backend_service", "parent_field": "backend_service"},
    "google_compute_target_http_proxy": {"parent_type": "google_compute_url_map", "parent_field": "url_map"},
    "google_compute_target_https_proxy": {"parent_type": "google_compute_url_map", "parent_field": "url_map"},
    "google_storage_bucket_object": {"parent_type": "google_storage_bucket", "parent_field": "bucket"},
    "google_storage_bucket_iam_binding": {"parent_type": "google_storage_bucket", "parent_field": "bucket"},
    "google_storage_bucket_iam_member": {"parent_type": "google_storage_bucket", "parent_field": "bucket"},
    "google_sql_database": {"parent_type": "google_sql_database_instance", "parent_field": "instance"},
    "google_sql_user": {"parent_type": "google_sql_database_instance", "parent_field": "instance"},
    "google_container_node_pool": {"parent_type": "google_container_cluster", "parent_field": "cluster"},
    "google_firestore_document": {"parent_type": "google_firestore_database", "parent_field": "database"},
    # --- Kubernetes ---
    "kubernetes_deployment": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_service": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_pod": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_daemonset": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_stateful_set": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_config_map": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_secret": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_service_account": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_role": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_role_binding": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_ingress": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_ingress_v1": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_network_policy": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_persistent_volume_claim": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_horizontal_pod_autoscaler": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_horizontal_pod_autoscaler_v2": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_job": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_cron_job": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_cron_job_v1": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_pod_disruption_budget": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_pod_disruption_budget_v1": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_limit_range": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_resource_quota": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_service_v1": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    "kubernetes_deployment_v1": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    # --- Oracle Cloud Infrastructure (OCI) ---
    "oci_core_subnet": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_vnic_attachment": {"parent_type": "oci_core_instance", "parent_field": "instance_id"},
    "oci_core_volume_attachment": {"parent_type": "oci_core_instance", "parent_field": "instance_id"},
    "oci_core_route_table": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_route_table_attachment": {"parent_type": "oci_core_subnet", "parent_field": "subnet_id"},
    "oci_core_security_list": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_dhcp_options": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_internet_gateway": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_nat_gateway": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_local_peering_gateway": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_service_gateway": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_network_security_group": {"parent_type": "oci_core_vcn", "parent_field": "vcn_id"},
    "oci_core_network_security_group_security_rule": {"parent_type": "oci_core_network_security_group", "parent_field": "network_security_group_id"},
    "oci_database_db_home": {"parent_type": "oci_database_db_system", "parent_field": "db_system_id"},
    "oci_database_database": {"parent_type": "oci_database_db_home", "parent_field": "db_home_id"},
    "oci_objectstorage_object": {"parent_type": "oci_objectstorage_bucket", "parent_field": "bucket"},
    "oci_objectstorage_preauthrequest": {"parent_type": "oci_objectstorage_bucket", "parent_field": "bucket"},
    "oci_objectstorage_object_lifecycle_policy": {"parent_type": "oci_objectstorage_bucket", "parent_field": "bucket"},
    "oci_containerengine_node_pool": {"parent_type": "oci_containerengine_cluster", "parent_field": "cluster_id"},
    "oci_identity_user_group_membership": {"parent_type": "oci_identity_group", "parent_field": "group_id"},
    "oci_identity_api_key": {"parent_type": "oci_identity_user", "parent_field": "user_id"},
    "oci_identity_auth_token": {"parent_type": "oci_identity_user", "parent_field": "user_id"},
    "oci_identity_customer_secret_key": {"parent_type": "oci_identity_user", "parent_field": "user_id"},
    "oci_identity_smtp_credential": {"parent_type": "oci_identity_user", "parent_field": "user_id"},
    "oci_kms_key_version": {"parent_type": "oci_kms_key", "parent_field": "key_id"},
    "oci_load_balancer_backend_set": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_load_balancer_backend": {"parent_type": "oci_load_balancer_backend_set", "parent_field": "backendset_name"},
    "oci_load_balancer_listener": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_load_balancer_certificate": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_load_balancer_rule_set": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_load_balancer_hostname": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_load_balancer_path_route_set": {"parent_type": "oci_load_balancer", "parent_field": "load_balancer_id"},
    "oci_network_load_balancer_backend_set": {"parent_type": "oci_network_load_balancer_network_load_balancer", "parent_field": "network_load_balancer_id"},
    "oci_network_load_balancer_backend": {"parent_type": "oci_network_load_balancer_backend_set", "parent_field": "backend_set_name"},
    "oci_network_load_balancer_listener": {"parent_type": "oci_network_load_balancer_network_load_balancer", "parent_field": "network_load_balancer_id"},
    "oci_nosql_index": {"parent_type": "oci_nosql_table", "parent_field": "table_name_or_id"},
    "oci_streaming_stream": {"parent_type": "oci_streaming_stream_pool", "parent_field": "stream_pool_id"},
    "oci_functions_function": {"parent_type": "oci_functions_application", "parent_field": "application_id"},
    "oci_file_storage_export": {"parent_type": "oci_file_storage_export_set", "parent_field": "export_set_id"},
    "oci_file_storage_mount_target": {"parent_type": "oci_core_subnet", "parent_field": "subnet_id"},
    # --- Alibaba Cloud ---
    "alicloud_vswitch": {"parent_type": "alicloud_vpc", "parent_field": "vpc_id"},
    "alicloud_instance": {"parent_type": "alicloud_vswitch", "parent_field": "vswitch_id"},
    "alicloud_network_interface": {"parent_type": "alicloud_vswitch", "parent_field": "vswitch_id"},
    "alicloud_network_interface_attachment": {"parent_type": "alicloud_instance", "parent_field": "instance_id"},
    "alicloud_security_group_rule": {"parent_type": "alicloud_security_group", "parent_field": "security_group_id"},
    "alicloud_db_database": {"parent_type": "alicloud_db_instance", "parent_field": "instance_id"},
    "alicloud_db_account": {"parent_type": "alicloud_db_instance", "parent_field": "instance_id"},
    "alicloud_db_account_privilege": {"parent_type": "alicloud_db_instance", "parent_field": "instance_id"},
    "alicloud_db_backup_policy": {"parent_type": "alicloud_db_instance", "parent_field": "instance_id"},
    "alicloud_db_connection": {"parent_type": "alicloud_db_instance", "parent_field": "instance_id"},
    "alicloud_oss_bucket_object": {"parent_type": "alicloud_oss_bucket", "parent_field": "bucket"},
    "alicloud_oss_bucket_acl": {"parent_type": "alicloud_oss_bucket", "parent_field": "bucket"},
    "alicloud_oss_bucket_policy": {"parent_type": "alicloud_oss_bucket", "parent_field": "bucket"},
    "alicloud_cs_kubernetes_node_pool": {"parent_type": "alicloud_cs_managed_kubernetes", "parent_field": "cluster_id"},
    "alicloud_slb_listener": {"parent_type": "alicloud_slb", "parent_field": "load_balancer_id"},
    "alicloud_slb_backend_server": {"parent_type": "alicloud_slb", "parent_field": "load_balancer_id"},
    "alicloud_slb_server_group": {"parent_type": "alicloud_slb", "parent_field": "load_balancer_id"},
    "alicloud_slb_rule": {"parent_type": "alicloud_slb_listener", "parent_field": "load_balancer_id"},
    "alicloud_slb_attachment": {"parent_type": "alicloud_slb", "parent_field": "load_balancer_id"},
    "alicloud_nat_gateway": {"parent_type": "alicloud_vpc", "parent_field": "vpc_id"},
    "alicloud_route_table": {"parent_type": "alicloud_vpc", "parent_field": "vpc_id"},
    "alicloud_route_entry": {"parent_type": "alicloud_route_table", "parent_field": "route_table_id"},
    "alicloud_forward_entry": {"parent_type": "alicloud_nat_gateway", "parent_field": "nat_gateway_id"},
    "alicloud_snat_entry": {"parent_type": "alicloud_nat_gateway", "parent_field": "snat_table_id"},
    "alicloud_ram_user_policy_attachment": {"parent_type": "alicloud_ram_user", "parent_field": "user_name"},
    "alicloud_ram_group_membership": {"parent_type": "alicloud_ram_group", "parent_field": "group_name"},
    "alicloud_ram_group_policy_attachment": {"parent_type": "alicloud_ram_group", "parent_field": "group_name"},
    "alicloud_ram_role_policy_attachment": {"parent_type": "alicloud_ram_role", "parent_field": "role_name"},
    "alicloud_kms_key_version": {"parent_type": "alicloud_kms_key", "parent_field": "key_id"},
    "alicloud_api_gateway_api": {"parent_type": "alicloud_api_gateway_group", "parent_field": "group_id"},
    "alicloud_api_gateway_app_attachment": {"parent_type": "alicloud_api_gateway_api", "parent_field": "api_id"},
    "alicloud_polardb_database": {"parent_type": "alicloud_polardb_cluster", "parent_field": "db_cluster_id"},
    "alicloud_polardb_account": {"parent_type": "alicloud_polardb_cluster", "parent_field": "db_cluster_id"},
    "alicloud_polardb_account_privilege": {"parent_type": "alicloud_polardb_cluster", "parent_field": "db_cluster_id"},
    "alicloud_kvstore_backup_policy": {"parent_type": "alicloud_kvstore_instance", "parent_field": "instance_id"},
    "alicloud_kvstore_account": {"parent_type": "alicloud_kvstore_instance", "parent_field": "instance_id"},
    "alicloud_alikafka_topic": {"parent_type": "alicloud_alikafka_instance", "parent_field": "instance_id"},
    "alicloud_alikafka_consumer_group": {"parent_type": "alicloud_alikafka_instance", "parent_field": "instance_id"},
    # --- DigitalOcean ---
    "digitalocean_droplet": {"parent_type": "digitalocean_vpc", "parent_field": "vpc_uuid"},
    "digitalocean_kubernetes_node_pool": {"parent_type": "digitalocean_kubernetes_cluster", "parent_field": "cluster_id"},
    "digitalocean_database_replica": {"parent_type": "digitalocean_database_cluster", "parent_field": "cluster_id"},
    "digitalocean_database_user": {"parent_type": "digitalocean_database_cluster", "parent_field": "cluster_id"},
    "digitalocean_database_db": {"parent_type": "digitalocean_database_cluster", "parent_field": "cluster_id"},
    "digitalocean_database_firewall": {"parent_type": "digitalocean_database_cluster", "parent_field": "cluster_id"},
    "digitalocean_database_connection_pool": {"parent_type": "digitalocean_database_cluster", "parent_field": "cluster_id"},
    "digitalocean_loadbalancer": {"parent_type": "digitalocean_vpc", "parent_field": "vpc_uuid"},
    "digitalocean_spaces_bucket_object": {"parent_type": "digitalocean_spaces_bucket", "parent_field": "bucket"},
    "digitalocean_spaces_bucket_cors_configuration": {"parent_type": "digitalocean_spaces_bucket", "parent_field": "bucket"},
    "digitalocean_record": {"parent_type": "digitalocean_domain", "parent_field": "domain"},
    "digitalocean_project_resources": {"parent_type": "digitalocean_project", "parent_field": "project"},
    "digitalocean_volume_attachment": {"parent_type": "digitalocean_droplet", "parent_field": "droplet_id"},
    "digitalocean_floating_ip_assignment": {"parent_type": "digitalocean_droplet", "parent_field": "droplet_id"},
    "digitalocean_reserved_ip_assignment": {"parent_type": "digitalocean_droplet", "parent_field": "droplet_id"},
    "digitalocean_container_registry_docker_credentials": {"parent_type": "digitalocean_container_registry", "parent_field": "registry_name"},
    # --- IBM Cloud ---
    "ibm_is_subnet": {"parent_type": "ibm_is_vpc", "parent_field": "vpc"},
    "ibm_is_security_group_rule": {"parent_type": "ibm_is_security_group", "parent_field": "group"},
    "ibm_is_network_acl": {"parent_type": "ibm_is_vpc", "parent_field": "vpc"},
    "ibm_is_network_acl_rule": {"parent_type": "ibm_is_network_acl", "parent_field": "network_acl"},
    "ibm_is_subnet_reserved_ip": {"parent_type": "ibm_is_subnet", "parent_field": "subnet"},
    "ibm_is_subnet_network_acl_attachment": {"parent_type": "ibm_is_subnet", "parent_field": "subnet"},
    "ibm_is_instance_volume_attachment": {"parent_type": "ibm_is_instance", "parent_field": "instance"},
    "ibm_is_instance_network_interface": {"parent_type": "ibm_is_instance", "parent_field": "instance"},
    "ibm_is_lb_listener": {"parent_type": "ibm_is_lb", "parent_field": "lb"},
    "ibm_is_lb_listener_policy": {"parent_type": "ibm_is_lb_listener", "parent_field": "listener"},
    "ibm_is_lb_listener_policy_rule": {"parent_type": "ibm_is_lb_listener_policy", "parent_field": "policy"},
    "ibm_is_lb_pool": {"parent_type": "ibm_is_lb", "parent_field": "lb"},
    "ibm_is_lb_pool_member": {"parent_type": "ibm_is_lb_pool", "parent_field": "pool"},
    "ibm_is_vpn_gateway_connection": {"parent_type": "ibm_is_vpn_gateway", "parent_field": "vpn_gateway"},
    "ibm_is_dedicated_host": {"parent_type": "ibm_is_dedicated_host_group", "parent_field": "dedicated_host_group"},
    "ibm_is_public_gateway": {"parent_type": "ibm_is_vpc", "parent_field": "vpc"},
    "ibm_is_vpc_routing_table": {"parent_type": "ibm_is_vpc", "parent_field": "vpc"},
    "ibm_is_vpc_routing_table_route": {"parent_type": "ibm_is_vpc_routing_table", "parent_field": "routing_table"},
    "ibm_is_vpc_address_prefix": {"parent_type": "ibm_is_vpc", "parent_field": "vpc"},
    "ibm_is_vpn_server_route": {"parent_type": "ibm_is_vpn_server", "parent_field": "vpn_server"},
    "ibm_is_endpoint_gateway_ip": {"parent_type": "ibm_is_endpoint_gateway", "parent_field": "endpoint_gateway"},
    "ibm_resource_key": {"parent_type": "ibm_resource_instance", "parent_field": "resource_instance_id"},
    "ibm_iam_access_group_policy": {"parent_type": "ibm_iam_access_group", "parent_field": "access_group_id"},
    "ibm_iam_access_group_members": {"parent_type": "ibm_iam_access_group", "parent_field": "access_group_id"},
    "ibm_iam_access_group_dynamic_rule": {"parent_type": "ibm_iam_access_group", "parent_field": "access_group_id"},
    "ibm_cos_bucket_object": {"parent_type": "ibm_cos_bucket", "parent_field": "bucket_name"},
    "ibm_container_cluster_worker_pool": {"parent_type": "ibm_container_cluster", "parent_field": "cluster_name_id"},
    "ibm_container_vpc_cluster_worker_pool": {"parent_type": "ibm_container_vpc_cluster", "parent_field": "cluster_name_id"},
    "ibm_container_worker_pool_zone_attachment": {"parent_type": "ibm_container_cluster_worker_pool", "parent_field": "worker_pool_id"},
    # --- Cloudflare ---
    "cloudflare_record": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_page_rule": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_firewall_rule": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_filter": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_rate_limit": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_worker_route": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_access_application": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_access_policy": {"parent_type": "cloudflare_access_application", "parent_field": "application_id"},
    "cloudflare_access_rule": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_waf_rule": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_waf_package": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_waf_group": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_zone_settings_override": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_zone_dnssec": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_certificate_pack": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_custom_ssl": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_custom_pages": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_logpush_job": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_ruleset": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_load_balancer": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_healthcheck": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_tunnel_config": {"parent_type": "cloudflare_tunnel", "parent_field": "tunnel_id"},
    "cloudflare_tunnel_route": {"parent_type": "cloudflare_tunnel", "parent_field": "tunnel_id"},
    "cloudflare_email_routing_rule": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_waiting_room": {"parent_type": "cloudflare_zone", "parent_field": "zone_id"},
    "cloudflare_waiting_room_event": {"parent_type": "cloudflare_waiting_room", "parent_field": "waiting_room_id"},
    # --- VMware vSphere ---
    "vsphere_virtual_machine": {"parent_type": "vsphere_resource_pool", "parent_field": "resource_pool_id"},
    "vsphere_resource_pool": {"parent_type": "vsphere_compute_cluster", "parent_field": "parent_resource_pool_id"},
    "vsphere_compute_cluster_host_group": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_compute_cluster_vm_group": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_compute_cluster_vm_host_rule": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_compute_cluster_vm_affinity_rule": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_compute_cluster_vm_anti_affinity_rule": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_host_port_group": {"parent_type": "vsphere_host_virtual_switch", "parent_field": "virtual_switch_name"},
    "vsphere_vnic": {"parent_type": "vsphere_host", "parent_field": "host_system_id"},
    "vsphere_vmfs_datastore": {"parent_type": "vsphere_host", "parent_field": "host_system_id"},
    "vsphere_folder": {"parent_type": "vsphere_datacenter", "parent_field": "datacenter_id"},
    "vsphere_distributed_port_group": {"parent_type": "vsphere_distributed_virtual_switch", "parent_field": "distributed_virtual_switch_uuid"},
    "vsphere_drs_vm_override": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_ha_vm_override": {"parent_type": "vsphere_compute_cluster", "parent_field": "compute_cluster_id"},
    "vsphere_datastore_cluster_vm_anti_affinity_rule": {"parent_type": "vsphere_datastore_cluster", "parent_field": "datastore_cluster_id"},
    "vsphere_storage_drs_vm_override": {"parent_type": "vsphere_datastore_cluster", "parent_field": "datastore_cluster_id"},
    "vsphere_content_library_item": {"parent_type": "vsphere_content_library", "parent_field": "library_id"},
    "vsphere_tag": {"parent_type": "vsphere_tag_category", "parent_field": "category_id"},
    # --- Helm ---
    "helm_release": {"parent_type": "kubernetes_namespace", "parent_field": "namespace"},
    # --- HashiCorp Vault ---
    "vault_kv_secret": {"parent_type": "vault_mount", "parent_field": "mount"},
    "vault_kv_secret_v2": {"parent_type": "vault_kv_secret_backend_v2", "parent_field": "mount"},
    "vault_pki_secret_backend_cert": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_pki_secret_backend_role": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_pki_secret_backend_root_cert": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_pki_secret_backend_intermediate_cert_request": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_pki_secret_backend_sign": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_database_secret_backend_connection": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_database_secret_backend_role": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_database_secret_backend_static_role": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_aws_auth_backend_role": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_aws_auth_backend_client": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_kubernetes_auth_backend_role": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_kubernetes_auth_backend_config": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_jwt_auth_backend_role": {"parent_type": "vault_jwt_auth_backend", "parent_field": "backend"},
    "vault_ldap_auth_backend_group": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_ldap_auth_backend_user": {"parent_type": "vault_auth_backend", "parent_field": "backend"},
    "vault_github_team": {"parent_type": "vault_github_auth_backend", "parent_field": "backend"},
    "vault_github_user": {"parent_type": "vault_github_auth_backend", "parent_field": "backend"},
    "vault_aws_secret_backend_role": {"parent_type": "vault_aws_secret_backend", "parent_field": "backend"},
    "vault_azure_secret_backend_role": {"parent_type": "vault_azure_secret_backend", "parent_field": "backend"},
    "vault_gcp_secret_roleset": {"parent_type": "vault_gcp_secret_backend", "parent_field": "backend"},
    "vault_gcp_secret_static_account": {"parent_type": "vault_gcp_secret_backend", "parent_field": "backend"},
    "vault_transit_secret_backend_key": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_ssh_secret_backend_role": {"parent_type": "vault_mount", "parent_field": "backend"},
    "vault_identity_group_member_entity_ids": {"parent_type": "vault_identity_group", "parent_field": "group_id"},
    "vault_identity_group_member_group_ids": {"parent_type": "vault_identity_group", "parent_field": "group_id"},
    "vault_identity_group_alias": {"parent_type": "vault_identity_group", "parent_field": "canonical_id"},
    "vault_identity_entity_alias": {"parent_type": "vault_identity_entity", "parent_field": "canonical_id"},
    "vault_identity_entity_policies": {"parent_type": "vault_identity_entity", "parent_field": "entity_id"},
    "vault_identity_oidc_role": {"parent_type": "vault_identity_oidc_key", "parent_field": "key"},
    # --- GitHub ---
    "github_repository_branch": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_branch_protection": {"parent_type": "github_repository", "parent_field": "repository_id"},
    "github_repository_branch_protection_v3": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_collaborator": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_webhook": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_deploy_key": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_file": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_milestone": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_tag_protection": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_ruleset": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_autolink_reference": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_environment": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_repository_environment_deployment_policy": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_actions_environment_secret": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_actions_environment_variable": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_actions_secret": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_actions_variable": {"parent_type": "github_repository", "parent_field": "repository"},
    "github_team_membership": {"parent_type": "github_team", "parent_field": "team_id"},
    "github_team_repository": {"parent_type": "github_team", "parent_field": "team_id"},
    "github_team_sync_group_mapping": {"parent_type": "github_team", "parent_field": "team_slug"},
    "github_team_settings": {"parent_type": "github_team", "parent_field": "team_id"},
    # --- Snowflake ---
    "snowflake_schema": {"parent_type": "snowflake_database", "parent_field": "database"},
    "snowflake_table": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_view": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_stage": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_procedure": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_function": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_sequence": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_stream": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_task": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_pipe": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_file_format": {"parent_type": "snowflake_schema", "parent_field": "schema"},
    "snowflake_database_grant": {"parent_type": "snowflake_database", "parent_field": "database_name"},
    "snowflake_schema_grant": {"parent_type": "snowflake_schema", "parent_field": "schema_name"},
    "snowflake_table_grant": {"parent_type": "snowflake_table", "parent_field": "table_name"},
    "snowflake_warehouse_grant": {"parent_type": "snowflake_warehouse", "parent_field": "warehouse_name"},
    "snowflake_role_grants": {"parent_type": "snowflake_role", "parent_field": "role_name"},
    # --- New Relic ---
    "newrelic_alert_condition": {"parent_type": "newrelic_alert_policy", "parent_field": "policy_id"},
    "newrelic_nrql_alert_condition": {"parent_type": "newrelic_alert_policy", "parent_field": "policy_id"},
    "newrelic_infra_alert_condition": {"parent_type": "newrelic_alert_policy", "parent_field": "policy_id"},
    "newrelic_synthetics_alert_condition": {"parent_type": "newrelic_alert_policy", "parent_field": "policy_id"},
    "newrelic_alert_policy_channel": {"parent_type": "newrelic_alert_policy", "parent_field": "policy_id"},
}


def get_parent_mapping(resource_type: str) -> Optional[Dict[str, str]]:
    """Return parent mapping for the given resource type, or None if no parent expected.

    Args:
        resource_type: Terraform resource type string (e.g. ``azurerm_subnet``).

    Returns:
        Dict with ``parent_type`` and ``parent_field`` keys, or ``None``.
    """
    if not resource_type:
        return None
    return HIERARCHY_CONFIG.get(resource_type.lower())
