secret:
  ignored_matches:
  - match: azurerm_key_vault
    name: ''
  - match: azurerm_key_vault_secret
    name: ''
  - match: azurerm_key_vault_key
    name: ''
  - match: azurerm_key_vault_certificate
    name: ''
  - match: aws_api_gateway_api_key
    name: ''
  - match: aws_api_gateway_usage_plan_key
    name: ''
  - match: oci_identity_api_key
    name: ''
  ignored_paths:
  - Scripts/Generate/icon_resolver.py
  - Scripts/Scan/test_*.py
  - Scripts/*_test.py
  - Scripts/Generate/test_*.py
  - Scripts/Tests/test_*.py
  - Scripts/*/test_*.py
version: 2
